#!/usr/bin/env bash                                                        
# a script that manages my processes                                       
# creating, displaying, stoping and deleting a file with a process         

Script="$1"

if [ -z "$Script" ]; then

	  echo "Usage: manage_my_process {start|stop|restart}"

fi

if [ "$Script" == "start" ]; then

	bash ./manage_my_process &

	echo "$!" > /var/run/my_process.pid

	echo "manage_my_process started"



elif [ "$Script" == "stop" ]; then

	[ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid

	echo "manage_my_process stopped"



elif [ "$Script" == "restart" ]; then

	"$0" stop >& /dev/null

	"$0" start >& /dev/null

	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}" 
fi
